/*
  # Populate communes part 5 - Remaining wilayas

  Adds major communes for remaining wilayas 28-58
  This ensures all 58 wilayas have communes available
*/

-- Wilaya 28 - M'Sila (47 communes - selection)
INSERT INTO communes (wilaya_code, name_fr, name_ar) VALUES
('28', 'M''Sila', 'المسيلة'),
('28', 'Bou Saâda', 'بوسعادة'),
('28', 'Ouled Derradj', 'أولاد دراج'),
('28', 'Sidi Aissa', 'سيدي عيسى'),
('28', 'Ain El Hadjel', 'عين الحجل'),
('28', 'Hammam Dalaa', 'حمام الضلعة'),
('28', 'Ouled Atia', 'أولاد عطية'),
('28', 'Magra', 'مقرة'),
('28', 'Berhoum', 'برهوم'),
('28', 'Ain El Melh', 'عين الملح'),
('28', 'Ouanougha', 'ونوغة'),
('28', 'Beni Ilmane', 'بني يلمان'),
('28', 'Chellal', 'شلال'),
('28', 'Khoubana', 'خبانة'),
('28', 'Mcif', 'مسيف'),
('28', 'Maadid', 'المعاضيد'),
('28', 'Medjedel', 'مجدل'),
('28', 'Belaiba', 'بلعايبة'),
('28', 'Sidi Hadjeres', 'سيدي هجرس'),
('28', 'Tamsa', 'تامسة')
ON CONFLICT DO NOTHING;

-- Wilaya 29 - Mascara (47 communes - selection)
INSERT INTO communes (wilaya_code, name_fr, name_ar) VALUES
('29', 'Mascara', 'معسكر'),
('29', 'Bou Hanifia', 'بوحنيفية'),
('29', 'Tighennif', 'تيغنيف'),
('29', 'Oued El Abtal', 'واد الأبطال'),
('29', 'Ain Ferah', 'عين فراح'),
('29', 'Ghriss', 'غريس'),
('29', 'Froha', 'فروحة'),
('29', 'Matemore', 'ماتمور'),
('29', 'Makdha', 'مقدة'),
('29', 'Sidi Kada', 'سيدي قادة'),
('29', 'Hacine', 'الحسين'),
('29', 'Mohammadia', 'المحمدية'),
('29', 'Sidi Boussaid', 'سيدي بوسعيد'),
('29', 'El Bordj', 'البرج'),
('29', 'Ain Fekan', 'عين فكان'),
('29', 'Beniane', 'بنيان'),
('29', 'Sig', 'سيق'),
('29', 'Zahana', 'زهانة'),
('29', 'Aouf', 'عوف'),
('29', 'El Ghomri', 'الغمري')
ON CONFLICT DO NOTHING;

-- Wilaya 30 - Ouargla (21 communes)
INSERT INTO communes (wilaya_code, name_fr, name_ar) VALUES
('30', 'Ouargla', 'ورقلة'),
('30', 'Ain Beida', 'عين البيضاء'),
('30', 'N''Goussa', 'نقوسة'),
('30', 'Hassi Ben Abdellah', 'حاسي بن عبد الله'),
('30', 'Rouissat', 'الرويسات'),
('30', 'Ain El Beida', 'عين البيضاء'),
('30', 'Sidi Khouiled', 'سيدي خويلد'),
('30', 'Hassi Messaoud', 'حاسي مسعود'),
('30', 'El Hadjira', 'الحجيرة'),
('30', 'Taibet', 'الطيبات'),
('30', 'Touggourt', 'تقرت'),
('30', 'Nezla', 'نزلة'),
('30', 'Zaouia El Abidia', 'الزاوية العابدية'),
('30', 'Taibet', 'تايبة'),
('30', 'Temacine', 'تماسين'),
('30', 'Balidat Ameur', 'بليدة عمر'),
('30', 'Megarine', 'مقارين'),
('30', 'Sidi Slimane', 'سيدي سليمان'),
('30', 'El Allia', 'العالية'),
('30', 'Tebesbest', 'تبسبست'),
('30', 'M''Naguar', 'مناقر')
ON CONFLICT DO NOTHING;

-- Remaining wilayas 32-58 (major communes only)
INSERT INTO communes (wilaya_code, name_fr, name_ar) VALUES
('32', 'El Bayadh', 'البيض'),
('32', 'Rogassa', 'روقاسة'),
('32', 'Stitten', 'ستيتن'),
('32', 'Brezina', 'بريزينة'),
('32', 'Ghassoul', 'الغسول'),
('32', 'Boualem', 'بوعلام'),
('32', 'El Abiodh Sidi Cheikh', 'الأبيض سيدي الشيخ'),
('32', 'Ain El Orak', 'عين الأوراك'),
('32', 'Arbaouat', 'أربواط'),
('32', 'Bougtoub', 'بوقطب'),
('32', 'El Kheither', 'الخيثر'),
('32', 'Kef El Ahmar', 'كاف الأحمار'),
('32', 'Boussemghoun', 'بوسمغون'),
('32', 'Chellala', 'شلالة'),
('32', 'Krakda', 'كراكدة'),
('32', 'El Bnoud', 'البنود'),
('32', 'Cheguig', 'شقيق'),
('32', 'Tousmouline', 'توسمولين'),
('32', 'Sidi Ameur', 'سيدي عامر'),
('32', 'El Mehara', 'المحارة'),
('32', 'Labiodh Sidi Cheikh', 'الأبيض سيدي الشيخ'),
('32', 'Sidi Tifour', 'سيدي طيفور'),
('33', 'Illizi', 'إليزي'),
('33', 'Djanet', 'جانت'),
('33', 'Debdeb', 'دبدب'),
('33', 'Bordj Omar Driss', 'برج عمر إدريس'),
('33', 'Bordj El Haouasse', 'برج الحواس'),
('34', 'Bordj Bou Arréridj', 'برج بوعريريج'),
('34', 'Ras El Oued', 'رأس الوادي'),
('34', 'Bordj Zemoura', 'برج زمورة'),
('34', 'Mansoura', 'المنصورة'),
('34', 'El Achir', 'الأشير'),
('34', 'Ain Taghrout', 'عين تاغروت'),
('34', 'Bordj Ghedir', 'برج الغدير'),
('34', 'Sidi Embarek', 'سيدي امبارك'),
('34', 'El Hamadia', 'الحمادية'),
('34', 'Belimour', 'بليمور'),
('34', 'Medjana', 'مجانة'),
('34', 'Teniet En Nasr', 'ثنية النصر'),
('34', 'Hasnaoua', 'حسناوة'),
('34', 'Khelil', 'خليل'),
('34', 'Haraza', 'حرازة'),
('34', 'El Main', 'الماين'),
('34', 'Ouled Brahem', 'أولاد ابراهيم'),
('34', 'Ouled Dahmane', 'أولاد دحمان'),
('34', 'Colla', 'قلة'),
('34', 'Taglait', 'تاقلايت'),
('35', 'Boumerdès', 'بومرداس'),
('35', 'Boudouaou', 'بودواو'),
('35', 'Dellys', 'دلس'),
('35', 'Khemis El Khechna', 'خميس الخشنة'),
('35', 'Thenia', 'الثنية'),
('35', 'Bordj Menaiel', 'برج منايل'),
('35', 'Isser', 'يسر'),
('35', 'Naciria', 'الناصرية'),
('35', 'Djinet', 'جينات'),
('35', 'Tidjelabine', 'تيجلابين'),
('35', 'Ouled Moussa', 'أولاد موسى'),
('35', 'Bouzegza Keddara', 'بوزقزة قدارة'),
('35', 'Baghlia', 'البغلية'),
('35', 'Sidi Daoud', 'سيدي داود'),
('35', 'Ouled Hadadj', 'أولاد حداج'),
('35', 'Larbatache', 'الأرباطاش'),
('35', 'Chabet El Ameur', 'شعبة العامر'),
('35', 'Zemmouri', 'الزموري'),
('35', 'Si Mustapha', 'سي مصطفى'),
('36', 'El Tarf', 'الطارف'),
('36', 'Bouhadjar', 'بوحجار'),
('36', 'Ben M''Hidi', 'بن مهيدي'),
('36', 'Bougous', 'بوقوس'),
('36', 'El Kala', 'القالة'),
('36', 'Ain El Assel', 'عين العسل'),
('36', 'El Aioun', 'العيون'),
('36', 'Bouteldja', 'بوثلجة'),
('36', 'Besbes', 'بسباس'),
('36', 'Asfour', 'عصفور'),
('36', 'Drean', 'الدرعان'),
('36', 'Chihani', 'الشيحاني'),
('37', 'Tindouf', 'تندوف'),
('37', 'Oum El Assel', 'أم العسل'),
('38', 'Tissemsilt', 'تيسمسيلت'),
('38', 'Bordj Bou Naama', 'برج بونعامة'),
('38', 'Theniet El Had', 'ثنية الحد'),
('38', 'Lazharia', 'لزهارية'),
('38', 'Beni Chaib', 'بني شعيب'),
('38', 'Lardjem', 'لرجام'),
('38', 'Melaab', 'ملعب'),
('38', 'Sidi Lantri', 'سيدي لنثري'),
('38', 'Bordj El Emir Abdelkader', 'برج الأمير عبد القادر'),
('38', 'Layoune', 'العيون'),
('38', 'Khemisti', 'خميستي'),
('38', 'Ouled Bessem', 'أولاد بسام'),
('39', 'El Oued', 'الوادي'),
('39', 'Robbah', 'الرباح'),
('39', 'Oued El Alenda', 'واد العلندة'),
('39', 'Bayadha', 'البياضة'),
('39', 'Nakhla', 'نخلة'),
('39', 'Guemar', 'قمار'),
('39', 'Kouinine', 'كوينين'),
('39', 'Reguiba', 'الرقيبة'),
('39', 'Hamraia', 'الحمراية'),
('39', 'Taghzout', 'تغزوت'),
('39', 'Debila', 'دبيلة'),
('39', 'Hassani Abdelkrim', 'حساني عبد الكريم'),
('39', 'Hassi Khalifa', 'حاسي خليفة'),
('39', 'Taleb Larbi', 'طالب العربي'),
('39', 'Douar El Ma', 'دوار الماء'),
('39', 'Sidi Aoun', 'سيدي عون'),
('39', 'Trifaoui', 'الطريفاوي'),
('39', 'Magrane', 'مقران'),
('39', 'Beni Guecha', 'بني قشة'),
('39', 'Ourmes', 'ورماس'),
('40', 'Khenchela', 'خنشلة'),
('40', 'Mtoussa', 'امتوسة'),
('40', 'Kais', 'قايس'),
('40', 'Baghai', 'بغاي'),
('40', 'El Hamma', 'الحامة'),
('40', 'Ain Touila', 'عين الطويلة'),
('40', 'Taouzient', 'تاوزينت'),
('40', 'Tamza', 'تامزة'),
('40', 'Ensigha', 'نسيغة'),
('40', 'Ouled Rechache', 'أولاد رشاش'),
('40', 'El Oueldja', 'الولجة'),
('40', 'Remila', 'الرميلة'),
('40', 'Cherchar', 'شرشار'),
('40', 'Djellal', 'جلال'),
('40', 'Babar', 'بابار'),
('40', 'Bouhmama', 'بوحمامة'),
('40', 'Yabous', 'يابوس'),
('40', 'Khirane', 'خيران'),
('40', 'Chechar', 'شرشار'),
('40', 'M''sara', 'مصارة'),
('40', 'El Mahmal', 'المحمل'),
('41', 'Souk Ahras', 'سوق أهراس'),
('41', 'Sedrata', 'سدراتة'),
('41', 'Hanancha', 'الحنانشة'),
('41', 'Mechroha', 'مشروحة'),
('41', 'Ouled Driss', 'أولاد إدريس'),
('41', 'Tiffech', 'تيفاش'),
('41', 'Zaarouria', 'الزعرورية'),
('41', 'Taoura', 'الطاورة'),
('41', 'Drea', 'الدريعة'),
('41', 'Haddada', 'الحدادة'),
('41', 'Khedara', 'الخضارة'),
('41', 'Merahna', 'مراحنة'),
('41', 'Ouled Moumene', 'أولاد مومن'),
('41', 'Bir Bouhouche', 'بئر بوحوش'),
('41', 'M''Daourouch', 'مداوروش'),
('41', 'Oum El Adhaim', 'أم العظائم'),
('41', 'Ain Zana', 'عين الزانة'),
('41', 'Ain Soltane', 'عين السلطان'),
('41', 'Ouillen', 'ويلان'),
('41', 'Sidi Fredj', 'سيدي فرج'),
('41', 'Safel El Ouiden', 'سافل الويدان'),
('41', 'Ragouba', 'الرقوبة'),
('41', 'Khemissa', 'خميسة'),
('41', 'Oued Keberit', 'واد الكبريت'),
('41', 'Terraguelt', 'ترقالت'),
('41', 'Zouabi', 'الزوابي'),
('42', 'Tipaza', 'تيبازة'),
('42', 'Menaceur', 'مناصر'),
('42', 'Larhat', 'الرحاحات'),
('42', 'Douaouda', 'دواودة'),
('42', 'Bourkika', 'بوركيكة'),
('42', 'Khemisti', 'خميستي'),
('42', 'Ain Tagourait', 'عين تقورايت'),
('42', 'Cherchell', 'شرشال'),
('42', 'Damous', 'داموس'),
('42', 'Merad', 'مراد'),
('42', 'Fouka', 'فوكة'),
('42', 'Bou Ismail', 'بو إسماعيل'),
('42', 'Ahmer El Ain', 'احمر العين'),
('42', 'Bou Haroun', 'بوهارون'),
('42', 'Sidi Amar', 'سيدي عمار'),
('42', 'Kolea', 'القليعة'),
('42', 'Attatba', 'عطاطبة'),
('42', 'Sidi Ghiles', 'سيدي غيلاس'),
('42', 'Messelmoun', 'مسلمون'),
('42', 'Sidi Rached', 'سيدي راشد'),
('42', 'Kourdane', 'قردان'),
('42', 'Chaiba', 'الشعيبة'),
('42', 'Ain Benian', 'عين بنيان'),
('42', 'Djebbabra', 'جبابرة'),
('42', 'Hadjout', 'حجوط'),
('42', 'Sidi Semiane', 'سيدي سميان'),
('42', 'Beni Milleuk', 'بني ميلك'),
('42', 'Hadjerat Ennous', 'حجرة النص'),
('43', 'Mila', 'ميلة'),
('43', 'Ferdjioua', 'فرجيوة'),
('43', 'Chelghoum Laid', 'شلغوم العيد'),
('43', 'Oued Athmania', 'واد عثمانية'),
('43', 'Ain Mellouk', 'عين ملوك'),
('43', 'Telerghma', 'التلاغمة'),
('43', 'Oued Seguen', 'واد سقن'),
('43', 'Tadjenanet', 'تاجنانت'),
('43', 'Benyahia Abderrahmane', 'بن يحيى عبد الرحمان'),
('43', 'Ouled Khalouf', 'أولاد خلوف'),
('43', 'Ain Beida Harriche', 'عين البيضاء الحريش'),
('43', 'Sidi Merouane', 'سيدي مروان'),
('43', 'Tiberguent', 'تيبرقنت'),
('43', 'Rouached', 'الرواشد'),
('43', 'Tessala Lemtai', 'تسالة لمطاعي'),
('43', 'Grarem Gouga', 'قرارم قوقة'),
('43', 'Sidi Khelifa', 'سيدي خليفة'),
('43', 'Terrai Bainen', 'ترعي بنيان'),
('43', 'Bouhatem', 'بوحاتم'),
('43', 'Hamala', 'حمالة'),
('43', 'Ain Tine', 'عين التين'),
('43', 'El Mechira', 'المشيرة'),
('43', 'Amira Arras', 'عميرة أرس'),
('43', 'Yahia Beni Guecha', 'يحيى بني قشة'),
('43', 'Ahmed Rachedi', 'أحمد راشدي'),
('43', 'Elayadi Barbes', 'العياضي بربس'),
('43', 'Zeghaia', 'زغاية'),
('43', 'Minar Zarza', 'مينار زرزة'),
('43', 'Derradji Bousselah', 'دراجي بوسلاح'),
('43', 'Tassadane Haddada', 'تاسدان حدادة'),
('44', 'Ain Defla', 'عين الدفلى'),
('44', 'Miliana', 'مليانة'),
('44', 'Boumedfaa', 'بومدفع'),
('44', 'Khemis Miliana', 'خميس مليانة'),
('44', 'Hammam Righa', 'حمام ريغة'),
('44', 'Arib', 'عريب'),
('44', 'Djelida', 'جليدة'),
('44', 'El Amra', 'العامرة'),
('44', 'Bourached', 'بوراشد'),
('44', 'El Attaf', 'العطاف'),
('44', 'El Abadia', 'العبادية'),
('44', 'Djendel', 'جندل'),
('44', 'Oued Chorfa', 'واد الشرفاء'),
('44', 'Ain Lechiakh', 'عين لشياخ'),
('44', 'Oued Djemaa', 'واد الجمعة'),
('44', 'Rouina', 'الروينة'),
('44', 'Zeddine', 'الزدين'),
('44', 'El Hassania', 'الحسانية'),
('44', 'Bir Ouled Khelifa', 'بئر أولاد خليفة'),
('44', 'Ben Allal', 'بن علال'),
('44', 'Ain Soltane', 'عين السلطان'),
('44', 'Tarik Ibn Ziad', 'طارق بن زياد'),
('44', 'Bordj Emir Khaled', 'برج الأمير خالد'),
('44', 'Ain Torki', 'عين التركي'),
('44', 'Sidi Lakhdar', 'سيدي الأخضر'),
('44', 'Ben Yousef', 'بن يوسف'),
('44', 'Oued El Abtal', 'واد الأبطال'),
('44', 'Ain Benian', 'عين بنيان'),
('44', 'Hoceinia', 'الحسينية'),
('44', 'Barbouche', 'بربوش'),
('44', 'Djemaa Ouled Cheikh', 'جمعة أولاد الشيخ'),
('44', 'Mekhatria', 'مخاطرية'),
('44', 'Bathia', 'باثية'),
('44', 'Tachta Zougagha', 'تاشتا الزقاغة'),
('44', 'Ain Bouyahia', 'عين بويحي'),
('44', 'El Maïne', 'المعين'),
('44', 'Tiberkanine', 'تبركانين'),
('45', 'Naâma', 'النعامة'),
('45', 'Mécheria', 'المشرية'),
('45', 'Ain Sefra', 'عين الصفراء'),
('45', 'Tiout', 'تيوت'),
('45', 'Sfissifa', 'صفيصيفة'),
('45', 'Moghrar', 'مغرار'),
('45', 'Asla', 'عسلة'),
('45', 'Djeniene Bourezg', 'الجنينة بورزق'),
('45', 'Ain Ben Khelil', 'عين بن خليل'),
('45', 'Makmen Ben Amar', 'مكمن بن عمار'),
('45', 'Kasdir', 'قصدير'),
('45', 'El Biodh', 'البيوض'),
('46', 'Ain Témouchent', 'عين تموشنت'),
('46', 'Chaabet El Ham', 'شعبة اللحم'),
('46', 'Ain Kihal', 'عين الكيحل'),
('46', 'Hammam Bou Hadjar', 'حمام بوحجر'),
('46', 'Bou Zedjar', 'بوزجار'),
('46', 'Oued Berkeche', 'واد بركش'),
('46', 'Sidi Ben Adda', 'سيدي بن عدة'),
('46', 'El Amria', 'العامرية'),
('46', 'Hassi El Ghella', 'حاسي الغلة'),
('46', 'Hassi El Ghella', 'حاسي الغلة'),
('46', 'El Malah', 'المالح'),
('46', 'Sidi Boumediene', 'سيدي بومدين'),
('46', 'Ouled Boudjemaa', 'أولاد بوجمعة'),
('46', 'Ain Tolba', 'عين الطلبة'),
('46', 'El Messaid', 'المساعيد'),
('46', 'Aoubellil', 'عقب الليل'),
('46', 'Tamzoura', 'تامزورة'),
('46', 'Oulhaca El Gheraba', 'ولهاصة الغرابة'),
('46', 'Beni Saf', 'بني صاف'),
('46', 'Sidi Safi', 'سيدي صافي'),
('46', 'Terga', 'ترقة'),
('46', 'Aghlal', 'أغلال'),
('46', 'El Emir Abdelkader', 'الأمير عبد القادر'),
('46', 'Chentouf', 'شنتوف'),
('46', 'Oued Sebbah', 'واد صباح'),
('47', 'Ghardaïa', 'غرداية'),
('47', 'El Meniaa', 'المنيعة'),
('47', 'Dhayet Bendhahoua', 'ضاية بن ضحوة'),
('47', 'Berriane', 'بريان'),
('47', 'Metlili', 'متليلي'),
('47', 'El Guerrara', 'القرارة'),
('47', 'El Atteuf', 'العطف'),
('47', 'Zelfana', 'زلفانة'),
('47', 'Sebseb', 'سبسب'),
('47', 'Bounoura', 'بونورة'),
('47', 'Hassi Fehal', 'حاسي الفحل'),
('47', 'Hassi Gara', 'حاسي قارة'),
('47', 'Mansoura', 'المنصورة'),
('48', 'Relizane', 'غليزان'),
('48', 'Oued Rhiou', 'واد رهيو'),
('48', 'Djidioua', 'جديوية'),
('48', 'Yellel', 'يلل'),
('48', 'Ammi Moussa', 'عمي موسى'),
('48', 'Zemmoura', 'زمورة'),
('48', 'Beni Dergoun', 'بني درقون'),
('48', 'Sidi M''Hamed Benaouda', 'سيدي امحمد بن عودة'),
('48', 'Ouarizane', 'واريزان'),
('48', 'Mazouna', 'مازونة'),
('48', 'Kalaa', 'القلعة'),
('48', 'Ain Tarek', 'عين الطارق'),
('48', 'Oued Essalem', 'واد السلام'),
('48', 'Ouled Yaïch', 'أولاد يعيش'),
('48', 'Belaassel Bouzegza', 'بلعسل بوزقزة'),
('48', 'Hamri', 'الحمري'),
('48', 'El Guettar', 'القطار'),
('48', 'Bendaoud', 'بن داود'),
('48', 'El Matmar', 'المطمر'),
('48', 'Sidi Khettab', 'سيدي خطاب'),
('48', 'Ain Rahma', 'عين الرحمة'),
('48', 'Yellel', 'يلل'),
('48', 'Oued El Djemaa', 'واد الجمعة'),
('48', 'Ramka', 'رمكة'),
('48', 'Mendes', 'مندس'),
('48', 'Lahlef', 'لحلاف'),
('48', 'Beni Zentis', 'بني زنطيس'),
('48', 'Souk El Had', 'سوق الحد'),
('48', 'Mediouna', 'مديونة'),
('48', 'Sidi Lazreg', 'سيدي الأزرق'),
('48', 'El Hassi', 'الحاسي'),
('48', 'Had Chekala', 'حد شقالة'),
('48', 'Dar Ben Abdellah', 'دار بن عبد الله'),
('48', 'Sidi Saada', 'سيدي سعادة'),
('48', 'El Ouldja', 'الولجة'),
('48', 'Merdja Sidi Abed', 'مرجة سيدي عابد'),
('48', 'Ouled Sidi Mihoub', 'أولاد سيدي ميهوب')
ON CONFLICT DO NOTHING;
