/*
  # Populate communes part 3 - Wilayas 13-20

  Adds communes for:
  - 13 Tlemcen (53 communes)
  - 14 Tiaret (42 communes)
  - 17 Djelfa (36 communes)
  - 18 Jijel (28 communes)
  - 20 Saïda (16 communes)
*/

-- Wilaya 13 - Tlemcen (53 communes)
INSERT INTO communes (wilaya_code, name_fr, name_ar) VALUES
('13', 'Tlemcen', 'تلمسان'),
('13', 'Beni Mester', 'بني مستار'),
('13', 'Ain Tallout', 'عين تالوت'),
('13', 'Remchi', 'الرمشي'),
('13', 'El Fehoul', 'الفحول'),
('13', 'Sabra', 'صبرة'),
('13', 'Ghazaouet', 'الغزوات'),
('13', 'Souani', 'السواني'),
('13', 'Djebala', 'جبالة'),
('13', 'El Gor', 'القور'),
('13', 'Oued Chouly', 'واد شولي'),
('13', 'Ain Fezza', 'عين فزة'),
('13', 'Ouled Mimoun', 'أولاد ميمون'),
('13', 'Amieur', 'عمير'),
('13', 'Ain Youcef', 'عين يوسف'),
('13', 'Zenata', 'زناتة'),
('13', 'Beni Snous', 'بني سنوس'),
('13', 'Bab El Assa', 'باب العسة'),
('13', 'Dar Yaghmouracene', 'دار يغمراسن'),
('13', 'Fellaoucene', 'فلاوسن'),
('13', 'Azails', 'عزايل'),
('13', 'Sebbaa Chioukh', 'سبعة شيوخ'),
('13', 'Terni Beni Hediel', 'ترني بني هديل'),
('13', 'Bensekrane', 'بن سكران'),
('13', 'Ain Nehala', 'عين نحالة'),
('13', 'Hennaya', 'الحناية'),
('13', 'Maghnia', 'مغنية'),
('13', 'Hammam Boughrara', 'حمام بوغرارة'),
('13', 'Souahlia', 'السواحلية'),
('13', 'M''Sirda Fouaga', 'مسيردة الفواقة'),
('13', 'Ain Fetah', 'عين فتاح'),
('13', 'El Aricha', 'العريشة'),
('13', 'Souk Thlata', 'سوق الثلاثاء'),
('13', 'Sidi Abdelli', 'سيدي عبد الله'),
('13', 'Sebdou', 'سبدو'),
('13', 'Beni Ouarsous', 'بني ورسوس'),
('13', 'Sidi Medjahed', 'سيدي مجاهد'),
('13', 'Beni Boussaid', 'بني بوسعيد'),
('13', 'Marsa Ben M''Hidi', 'مرسى بن مهيدي'),
('13', 'Nedroma', 'ندرومة'),
('13', 'Sidi Djillali', 'سيدي جيلالي'),
('13', 'Beni Bahdel', 'بني بهدل'),
('13', 'El Bouihi', 'البويهي'),
('13', 'Honaine', 'هنين'),
('13', 'Tianet', 'تيانت'),
('13', 'Ouled Riyah', 'أولاد رياح'),
('13', 'Bouhlou', 'بوحلو'),
('13', 'Souk El Khemis', 'سوق الخميس'),
('13', 'Ain Ghoraba', 'عين غرابة'),
('13', 'Chetouane', 'شتوان'),
('13', 'Mansourah', 'المنصورة'),
('13', 'Beni Semiel', 'بني سميل'),
('13', 'Ain Kebira', 'عين الكبيرة')
ON CONFLICT DO NOTHING;

-- Wilaya 14 - Tiaret (42 communes)
INSERT INTO communes (wilaya_code, name_fr, name_ar) VALUES
('14', 'Tiaret', 'تيارت'),
('14', 'Medroussa', 'مدروسة'),
('14', 'Ain Bouchekif', 'عين بوشقيف'),
('14', 'Sidi Ali Mellal', 'سيدي علي ملال'),
('14', 'Ain Zarit', 'عين الذهب'),
('14', 'Ain Deheb', 'عين الذهب'),
('14', 'Sidi Bakhti', 'سيدي بختي'),
('14', 'Medrissa', 'مدريسة'),
('14', 'Zmalet El Emir Abdelkader', 'زمالة الأمير عبد القادر'),
('14', 'Madna', 'المادنة'),
('14', 'Sebt', 'السبت'),
('14', 'Mellakou', 'ملاكو'),
('14', 'Dahmouni', 'دحموني'),
('14', 'Rahouia', 'رحوية'),
('14', 'Mahdia', 'مهدية'),
('14', 'Sougueur', 'سوقر'),
('14', 'Sidi Abderrahmane', 'سيدي عبد الرحمان'),
('14', 'Djillali Ben Amar', 'جيلالي بن عمار'),
('14', 'Ain El Hadid', 'عين الحديد'),
('14', 'Sebaine', 'السبعين'),
('14', 'Tousnina', 'توسنينة'),
('14', 'Frenda', 'فرندة'),
('14', 'Ain Kermes', 'عين كرمس'),
('14', 'Ksar Chellala', 'قصر الشلالة'),
('14', 'Rechaiga', 'الرشايقة'),
('14', 'Nadorah', 'الناظورة'),
('14', 'Tagdemt', 'تاقدمت'),
('14', 'Oued Lilli', 'واد ليلي'),
('14', 'Mechraâ Safa', 'مشرع الصفا'),
('14', 'Hamadia', 'حمادية'),
('14', 'Chehaima', 'الشحيمة'),
('14', 'Takhemaret', 'تاخمرت'),
('14', 'Sidi Hosni', 'سيدي حسني'),
('14', 'Meghila', 'مغيلة'),
('14', 'Guertoufa', 'قرطوفة'),
('14', 'Serghine', 'سرغين'),
('14', 'Bougara', 'بوقرة'),
('14', 'Faidja', 'فايجة'),
('14', 'Tidda', 'تيدة'),
('14', 'Sidi Abdelghani', 'سيدي عبد الغني'),
('14', 'Naima', 'نعيمة'),
('14', 'Djebabra', 'جبابرة')
ON CONFLICT DO NOTHING;

-- Wilaya 17 - Djelfa (36 communes)
INSERT INTO communes (wilaya_code, name_fr, name_ar) VALUES
('17', 'Djelfa', 'الجلفة'),
('17', 'Moudjebara', 'مجبارة'),
('17', 'El Guedid', 'القديد'),
('17', 'Hassi Bahbah', 'حاسي بحبح'),
('17', 'Ain Maabed', 'عين معبد'),
('17', 'Sed Rahal', 'سد الرحال'),
('17', 'Feidh El Botma', 'فيض البطمة'),
('17', 'Birine', 'بيرين'),
('17', 'Bouira Lahdab', 'بويرة الأحداب'),
('17', 'Zaccar', 'زكار'),
('17', 'El Khemis', 'الخميس'),
('17', 'Sidi Baizid', 'سيدي بايزيد'),
('17', 'M''Liliha', 'مليليحة'),
('17', 'El Idrissia', 'الإدريسية'),
('17', 'Douis', 'دويس'),
('17', 'Hassi El Euch', 'حاسي العش'),
('17', 'Messaad', 'مسعد'),
('17', 'Guettara', 'قطارة'),
('17', 'Sidi Ladjel', 'سيدي لعجال'),
('17', 'Had Sahary', 'حد الصحاري'),
('17', 'Guernini', 'قرنيني'),
('17', 'Selmana', 'سلمانة'),
('17', 'Ain Chouhada', 'عين الشهداء'),
('17', 'Oum Laadham', 'أم العظام'),
('17', 'Dar Chioukh', 'دار الشيوخ'),
('17', 'Charef', 'الشارف'),
('17', 'Beni Yagoub', 'بني يعقوب'),
('17', 'Zaafrane', 'الزعفران'),
('17', 'Deldoul', 'دلدول'),
('17', 'Ain Oussera', 'عين وسارة'),
('17', 'Benhar', 'بنهار'),
('17', 'Hassi Fedoul', 'حاسي الفضول'),
('17', 'Amourah', 'عمورة'),
('17', 'Ain El Ibel', 'عين الإبل'),
('17', 'Tadmit', 'تادميت'),
('17', 'El Bira', 'البيرة')
ON CONFLICT DO NOTHING;

-- Wilaya 18 - Jijel (28 communes)
INSERT INTO communes (wilaya_code, name_fr, name_ar) VALUES
('18', 'Jijel', 'جيجل'),
('18', 'Eraguene', 'العراقين'),
('18', 'El Aouana', 'العوانة'),
('18', 'Ziama Mansouriah', 'زيامة منصورية'),
('18', 'Taher', 'الطاهير'),
('18', 'Emir Abdelkader', 'الأمير عبد القادر'),
('18', 'Chekfa', 'الشقفة'),
('18', 'Chahna', 'الشحنة'),
('18', 'El Milia', 'الميلية'),
('18', 'Sidi Maarouf', 'سيدي معروف'),
('18', 'Settara', 'سطارة'),
('18', 'El Ancer', 'العنصر'),
('18', 'Sidi Abdelaziz', 'سيدي عبد العزيز'),
('18', 'Kaous', 'القاوس'),
('18', 'Ghebala', 'الغبالة'),
('18', 'Bouraoui Belhadef', 'بوراوي بلهادف'),
('18', 'Djimla', 'جيملة'),
('18', 'Selma Benziada', 'سلمى بن زيادة'),
('18', 'Boussif Ouled Askeur', 'بوسيف أولاد عسكر'),
('18', 'El Kennar Nouchfi', 'القنار نوشفي'),
('18', 'Ouled Yahia Khadrouche', 'أولاد يحيى خدروش'),
('18', 'Boudria Beni Yadjis', 'بودرية بني ياجيس'),
('18', 'Kheiri Oued Adjoul', 'خيري واد عجول'),
('18', 'Texenna', 'تاكسنة'),
('18', 'Djemaa Beni Habibi', 'جمعة بني حبيبي'),
('18', 'Bordj Taher', 'برج الطاهر'),
('18', 'Ouled Rabah', 'أولاد رابح'),
('18', 'Ouadjana', 'وجانة')
ON CONFLICT DO NOTHING;

-- Wilaya 20 - Saïda (16 communes)
INSERT INTO communes (wilaya_code, name_fr, name_ar) VALUES
('20', 'Saïda', 'سعيدة'),
('20', 'Doui Thabet', 'دوي ثابت'),
('20', 'Ain El Hadjar', 'عين الحجر'),
('20', 'Ouled Khaled', 'أولاد خالد'),
('20', 'Moulay Larbi', 'مولاي العربي'),
('20', 'Youb', 'يوب'),
('20', 'Hounet', 'حونت'),
('20', 'Sidi Amar', 'سيدي عمار'),
('20', 'Sidi Boubekeur', 'سيدي بوبكر'),
('20', 'El Hassasna', 'الحساسنة'),
('20', 'Maamora', 'المعمورة'),
('20', 'Sidi Ahmed', 'سيدي أحمد'),
('20', 'Ain Sekhouna', 'عين سخونة'),
('20', 'Ouled Brahim', 'أولاد إبراهيم'),
('20', 'Tircine', 'تيرسين'),
('20', 'Ain Soltane', 'عين السلطان')
ON CONFLICT DO NOTHING;
