/*
  # Populate communes part 4 - Wilayas 21-30

  Adds communes for:
  - 21 Skikda (38 communes)
  - 22 Sidi Bel Abbès (52 communes)
  - 24 Guelma (34 communes)
  - 26 Médéa (64 communes)
  - 27 Mostaganem (32 communes)
  - 28 M'Sila (47 communes)
  - 29 Mascara (47 communes)
  - 30 Ouargla (21 communes)
*/

-- Wilaya 21 - Skikda (38 communes)
INSERT INTO communes (wilaya_code, name_fr, name_ar) VALUES
('21', 'Skikda', 'سكيكدة'),
('21', 'Ain Zouit', 'عين الزويت'),
('21', 'El Hadaiek', 'الحدائق'),
('21', 'Azzaba', 'عزابة'),
('21', 'Djendel Saadi Mohamed', 'جندل سعدي محمد'),
('21', 'Ain Cherchar', 'عين الشرشار'),
('21', 'Bekkouche Lakhdar', 'بكوش لخضر'),
('21', 'Beni Zid', 'بني زيد'),
('21', 'Kerkera', 'كركرة'),
('21', 'Ouled Attia', 'أولاد عطية'),
('21', 'Oued Zehour', 'واد الزهور'),
('21', 'Collo', 'القل'),
('21', 'Beni Oulbane', 'بني ولبان'),
('21', 'Zitouna', 'الزيتونة'),
('21', 'El Harrouch', 'الحروش'),
('21', 'Ramdane Djamel', 'رمضان جمال'),
('21', 'Ouled Hbaba', 'أولاد حبابة'),
('21', 'Sidi Mezghiche', 'سيدي مزغيش'),
('21', 'Emdjez Edchich', 'مجاز الدشيش'),
('21', 'Beni Bechir', 'بني بشير'),
('21', 'Salah Bouchaour', 'صالح بوشعور'),
('21', 'Tamalous', 'تمالوس'),
('21', 'Ain Bouziane', 'عين بوزيان'),
('21', 'Ramdane Djamel', 'رمضان جمال'),
('21', 'Kanoua', 'قانوة'),
('21', 'Es Sebt', 'السبت'),
('21', 'Ouled Hbaba', 'أولاد حبابة'),
('21', 'Fil Fila', 'الفيل فيلة'),
('21', 'Cheraia', 'الشرايع'),
('21', 'Zerdazas', 'زردازس'),
('21', 'Ouled Attia', 'أولاد عطية'),
('21', 'Oum Toub', 'أم الطوب'),
('21', 'Ain Kechra', 'عين كشرة'),
('21', 'Ouldja Boulbalout', 'ولجة بولبلوط'),
('21', 'Hammadi Krouma', 'حمادي كرومة'),
('21', 'El Ghedir', 'الغدير'),
('21', 'Bouchtata', 'بوشتاتة'),
('21', 'Khenguet Sidi Nadji', 'خنقة سيدي ناجي')
ON CONFLICT DO NOTHING;

-- Wilaya 22 - Sidi Bel Abbès (52 communes)
INSERT INTO communes (wilaya_code, name_fr, name_ar) VALUES
('22', 'Sidi Bel Abbès', 'سيدي بلعباس'),
('22', 'Tessala', 'تسالة'),
('22', 'Sidi Brahim', 'سيدي ابراهيم'),
('22', 'Mostefa Ben Brahim', 'مصطفى بن براهيم'),
('22', 'Telagh', 'تلاغ'),
('22', 'Mezaourou', 'مزاورو'),
('22', 'Boukhanafis', 'بوخنافس'),
('22', 'Sidi Ali Boussidi', 'سيدي علي بوسيدي'),
('22', 'Badredine El Mokrani', 'بدر الدين المقراني'),
('22', 'Marhoum', 'مرحوم'),
('22', 'Tafissour', 'تافسور'),
('22', 'Amarnas', 'عمارنس'),
('22', 'Tilmouni', 'تلموني'),
('22', 'Sidi Lahcene', 'سيدي لحسن'),
('22', 'Ain Thrid', 'عين ذريد'),
('22', 'Merine', 'مرين'),
('22', 'Ras El Ma', 'رأس الماء'),
('22', 'Ain Tindamine', 'عين تندامين'),
('22', 'Ain Kada', 'عين قادة'),
('22', 'Mcid', 'مسيد'),
('22', 'Sidi Khaled', 'سيدي خالد'),
('22', 'Ain El Berd', 'عين البرد'),
('22', 'Sfissef', 'صفيصف'),
('22', 'Ain Adden', 'عين عدن'),
('22', 'Oued Sefioun', 'واد سفيون'),
('22', 'Moulay Slissen', 'مولاي سليسن'),
('22', 'El Hacaiba', 'الحصايبة'),
('22', 'Hassi Zehana', 'حاسي زهانة'),
('22', 'Tabia', 'الطابية'),
('22', 'Merine', 'مرين'),
('22', 'Ras El Ma', 'رأس الماء'),
('22', 'Sehala', 'سهالة'),
('22', 'Sidi Yacoub', 'سيدي يعقوب'),
('22', 'Sidi Hamadouche', 'سيدي حمادوش'),
('22', 'Bir El Hammam', 'بئر الحمام'),
('22', 'Sidi Ali Benyoub', 'سيدي علي بن يوب'),
('22', 'Sidi Dahou Djedid', 'سيدي ضهو الجديد'),
('22', 'Lamtar', 'لامطار'),
('22', 'Ain Trid', 'عين ذريد'),
('22', 'Makedra', 'مقدرة'),
('22', 'Tenira', 'تنيرة'),
('22', 'Moulay Slissen', 'مولاي سليسن'),
('22', 'El Hacaiba', 'الحصايبة'),
('22', 'Hassi Dahou', 'حاسي دحو'),
('22', 'Hassi Zehana', 'حاسي زهانة'),
('22', 'Tabia', 'الطابية'),
('22', 'Merine', 'مرين'),
('22', 'Teghalimet', 'تغليمت'),
('22', 'Sidi Chaib', 'سيدي شعيب'),
('22', 'Boudjebaa El Bordj', 'بوجبع البرج'),
('22', 'Amarnas', 'عمارنس'),
('22', 'Oued Taourira', 'واد التاوريرة')
ON CONFLICT DO NOTHING;

-- Wilaya 24 - Guelma (34 communes)
INSERT INTO communes (wilaya_code, name_fr, name_ar) VALUES
('24', 'Guelma', 'قالمة'),
('24', 'Nechmaya', 'نشماية'),
('24', 'Bouati Mahmoud', 'بوعاتي محمود'),
('24', 'Oued Zenati', 'واد الزناتي'),
('24', 'Tamlouka', 'تاملوكة'),
('24', 'Oued Fragha', 'واد فراقة'),
('24', 'Ain Sandel', 'عين صندل'),
('24', 'Ras El Agba', 'رأس العقبة'),
('24', 'Dahouara', 'دهوارة'),
('24', 'Belkheir', 'بلخير'),
('24', 'Ben Djarrah', 'بن جراح'),
('24', 'Bou Hamdane', 'بوحمدان'),
('24', 'Ain Ben Beida', 'عين بن بيضة'),
('24', 'Khezarra', 'الخزارة'),
('24', 'Hammam Debagh', 'حمام دباغ'),
('24', 'Bouchegouf', 'بوشقوف'),
('24', 'Hammam N''Bails', 'حمام النبايل'),
('24', 'Ain Makhlouf', 'عين مخلوف'),
('24', 'Ain Larbi', 'عين العربي'),
('24', 'Fedjoudj', 'فجوج'),
('24', 'Bordj Sabath', 'برج صباط'),
('24', 'Hammam Ouled Ali', 'حمام أولاد علي'),
('24', 'Medjez Amar', 'مجاز عمار'),
('24', 'Bou Hachana', 'بوحشانة'),
('24', 'Roknia', 'الركنية'),
('24', 'Sellaoua Announa', 'سلاوة عنونة'),
('24', 'Bouati Mahmoud', 'بوعاتي محمود'),
('24', 'Heliopolis', 'هيليوبوليس'),
('24', 'Ain Reggada', 'عين الرقادة'),
('24', 'Oued Cheham', 'واد الشحوم'),
('24', 'Djeballah Khemissi', 'جبالة خميسي'),
('24', 'Belkheir', 'بلخير'),
('24', 'El Fedjoudj', 'الفجوج'),
('24', 'Houari Boumediene', 'هواري بومدين')
ON CONFLICT DO NOTHING;

-- Wilaya 26 - Médéa (64 communes - selection)
INSERT INTO communes (wilaya_code, name_fr, name_ar) VALUES
('26', 'Médéa', 'المدية'),
('26', 'Ouzera', 'وزرة'),
('26', 'Ouled Antar', 'أولاد عنتر'),
('26', 'Ain Boucif', 'عين بوسيف'),
('26', 'Derrag', 'دراق'),
('26', 'El Guelb El Kebir', 'القلب الكبير'),
('26', 'Beni Slimane', 'بني سليمان'),
('26', 'Berrouaghia', 'البرواقية'),
('26', 'Seghouane', 'السغوان'),
('26', 'Sidi Naamane', 'سيدي نعمان'),
('26', 'Tablat', 'تابلاط'),
('26', 'Ksar El Boukhari', 'قصر البخاري'),
('26', 'El Omaria', 'العمارية'),
('26', 'Ouled Brahim', 'أولاد إبراهيم'),
('26', 'Ouled Hellal', 'أولاد هلال'),
('26', 'Tamesguida', 'تمسقيدة'),
('26', 'El Azizia', 'العزيزية'),
('26', 'Souagui', 'سواقي'),
('26', 'Tizi Mahdi', 'تيزي مهدي'),
('26', 'Sidi Zahar', 'سيدي زهار'),
('26', 'Sidi Errabia', 'سيدي الربيع'),
('26', 'Baata', 'بعطة'),
('26', 'Benchicao', 'بن شكاو'),
('26', 'Chahbounia', 'الشهبونية'),
('26', 'El Hamdania', 'الحمدانية'),
('26', 'Boghar', 'بوغار'),
('26', 'Ain Ouksir', 'عين أقصير'),
('26', 'Cheniguel', 'شنيقل'),
('26', 'Ain Boucif', 'عين بوسيف'),
('26', 'Hannacha', 'حناشة')
ON CONFLICT DO NOTHING;

-- Wilaya 27 - Mostaganem (32 communes)
INSERT INTO communes (wilaya_code, name_fr, name_ar) VALUES
('27', 'Mostaganem', 'مستغانم'),
('27', 'Sayada', 'صيادة'),
('27', 'Fornaka', 'فرناكة'),
('27', 'Stidia', 'ستيدية'),
('27', 'Ain Tedles', 'عين تادلس'),
('27', 'Hassi Mameche', 'حاسي ماماش'),
('27', 'Sour', 'صور'),
('27', 'Mesra', 'مسرة'),
('27', 'Ain Nouissy', 'عين النويصي'),
('27', 'Kheiredine', 'خير الدين'),
('27', 'Sidi Ali', 'سيدي علي'),
('27', 'Abdelmalek Ramdane', 'عبد المالك رمضان'),
('27', 'Hadjadj', 'حجاج'),
('27', 'Nekmaria', 'النقمارية'),
('27', 'Sidi Bellatar', 'سيدي بلاطار'),
('27', 'Khadra', 'خضراء'),
('27', 'Sidi Lakhdar', 'سيدي الأخضر'),
('27', 'Achaacha', 'عشعاشة'),
('27', 'Kheirreddine', 'خير الدين'),
('27', 'Bouguirat', 'بوقرة'),
('27', 'Sidi Belattar', 'سيدي بلاطار'),
('27', 'Mazagran', 'مازغران'),
('27', 'Hassi Mamèche', 'حاسي ماماش'),
('27', 'Oued El Kheir', 'واد الخير'),
('27', 'Ain Boudinar', 'عين بودينار'),
('27', 'Touahria', 'طواهرية'),
('27', 'Sirat', 'صيرات'),
('27', 'Ain Sidi Cherif', 'عين سيدي الشريف'),
('27', 'Mesra', 'مسرة'),
('27', 'Mansourah', 'المنصورة'),
('27', 'Souaflia', 'السوافلية'),
('27', 'Tazgait', 'تازقايت')
ON CONFLICT DO NOTHING;
